name = "Fundamentally Optimized"
author = "holybaechu"
version = "1.0.0+1.21.8.fabric"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "051b42f285059b04568545868a45640a8061616849de8394eadcfebfa106e280"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.6"]
