name = "Fundamentally Optimized"
author = "holybaechu"
version = "1.0.0+1.8.9.forge"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a4d26623f2e009bea8008e83e65ceb9c92e2d0bb4eb02f144eabf60eb3245143"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
