name: 'Validate Tag Format'
description: 'Validates that the current ref is a properly formatted tag'

inputs:
  pattern:
    description: 'Regex pattern to validate tag format'
    required: false
    default: '^[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+\.[0-9]+\.[0-9]+\.(fabric|forge)$'

outputs:
  valid:
    description: 'Boolean indicating if the current ref is a valid tag'
    value: ${{ steps.validate.outputs.valid }}
  tag:
    description: 'The clean tag name (without refs/tags/ prefix)'
    value: ${{ steps.validate.outputs.tag }}
  version:
    description: 'Extracted pack version from tag'
    value: ${{ steps.validate.outputs.version }}
  mc-version:
    description: 'Extracted Minecraft version from tag'
    value: ${{ steps.validate.outputs.mc-version }}
  modloader:
    description: 'Extracted modloader from tag'
    value: ${{ steps.validate.outputs.modloader }}

runs:
  using: 'composite'
  steps:
    - name: Validate tag format
      id: validate
      shell: bash
      run: |
        echo "GITHUB_REF: $GITHUB_REF"
        echo "GITHUB_REF_TYPE: $GITHUB_REF_TYPE"
        echo "GITHUB_REF_NAME: $GITHUB_REF_NAME"
        
        if [[ "$GITHUB_REF_TYPE" != "tag" ]]; then
          echo "Not a tag push, skipping validation"
          echo "valid=false" >> $GITHUB_OUTPUT
          exit 0
        fi
        
        TAG="$GITHUB_REF_NAME"
        echo "Tag name: $TAG"
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        
        if [[ $TAG =~ ${{ inputs.pattern }} ]]; then
          echo "✅ Tag format is valid: $TAG"
          echo "valid=true" >> $GITHUB_OUTPUT
          
          PACK_VERSION=$(echo "$TAG" | cut -d'+' -f1)

          MC_MODLOADER_PART=$(echo "$TAG" | cut -d'+' -f2)
          MODLOADER=$(echo "$MC_MODLOADER_PART" | sed 's/.*\.//')
          MINECRAFT_VERSION=$(echo "$MC_MODLOADER_PART" | sed 's/\.[^.]*$//')
          
          echo "version=$PACK_VERSION" >> $GITHUB_OUTPUT
          echo "mc-version=$MINECRAFT_VERSION" >> $GITHUB_OUTPUT
          echo "modloader=$MODLOADER" >> $GITHUB_OUTPUT
          
          echo "Pack version: $PACK_VERSION"
          echo "Minecraft version: $MINECRAFT_VERSION"
          echo "Modloader: $MODLOADER"
        else
          echo "❌ Tag format is invalid: $TAG"
          echo "Expected format: x.y.z+a.b.c.modloader (e.g., 1.0.0+1.21.8.fabric)"
          echo "valid=false" >> $GITHUB_OUTPUT
        fi
